# Note that we don't need to "turn on" the heartbeat because grow is present.
# I made these the size of the cluster so we trigger scaling at least once
# We currently assume these are uniform (so no order enforced beyond the listing here)
jobs:
  - name: echo
    command: echo hello world
    count: 5
    nodes: 1

  # Note that this takes up the entirety of our 4 node faux
  # test cluster, so the grow will trigger when the queue time
  # stacks up
  - name: sleep
    command: sleep 100
    count: 10
    nodes: 4

  # TODO need a test case for queue time waiting...
  # Also need to implement when with < > case.
  - name: big-sleep
    command: sleep 10
    count: 5
    nodes: 10

rules:
  # 1. This rule says to submit the sleep jobs when we start
  - trigger: start
    action:
      name: submit
      label: echo

  # This says to submit the sleep jobs when we have 5 successful echo
  - trigger: metric
    name: count.echo.success
    when: 5
    action:
      name: submit
      label: sleep

  # When the pending time of sleep is > 5 seconds, grow the cluster.
  - trigger: metric
    name: pending-duration.mean
    when: "> 5"
    action:
      name: grow
