# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ensemble_service_pb2 as ensemble__service__pb2

GRPC_GENERATED_VERSION = "1.66.2"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in ensemble_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class EnsembleOperatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestUpdate = channel.unary_unary(
            "/convergedcomputing.org.grpc.v1.EnsembleOperator/RequestUpdate",
            request_serializer=ensemble__service__pb2.UpdateRequest.SerializeToString,
            response_deserializer=ensemble__service__pb2.Response.FromString,
            _registered_method=True,
        )
        self.RequestStatus = channel.unary_unary(
            "/convergedcomputing.org.grpc.v1.EnsembleOperator/RequestStatus",
            request_serializer=ensemble__service__pb2.StatusRequest.SerializeToString,
            response_deserializer=ensemble__service__pb2.Response.FromString,
            _registered_method=True,
        )
        self.RequestAction = channel.unary_unary(
            "/convergedcomputing.org.grpc.v1.EnsembleOperator/RequestAction",
            request_serializer=ensemble__service__pb2.ActionRequest.SerializeToString,
            response_deserializer=ensemble__service__pb2.Response.FromString,
            _registered_method=True,
        )


class EnsembleOperatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RequestStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RequestAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EnsembleOperatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RequestUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.RequestUpdate,
            request_deserializer=ensemble__service__pb2.UpdateRequest.FromString,
            response_serializer=ensemble__service__pb2.Response.SerializeToString,
        ),
        "RequestStatus": grpc.unary_unary_rpc_method_handler(
            servicer.RequestStatus,
            request_deserializer=ensemble__service__pb2.StatusRequest.FromString,
            response_serializer=ensemble__service__pb2.Response.SerializeToString,
        ),
        "RequestAction": grpc.unary_unary_rpc_method_handler(
            servicer.RequestAction,
            request_deserializer=ensemble__service__pb2.ActionRequest.FromString,
            response_serializer=ensemble__service__pb2.Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "convergedcomputing.org.grpc.v1.EnsembleOperator", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "convergedcomputing.org.grpc.v1.EnsembleOperator", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class EnsembleOperator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/convergedcomputing.org.grpc.v1.EnsembleOperator/RequestUpdate",
            ensemble__service__pb2.UpdateRequest.SerializeToString,
            ensemble__service__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RequestStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/convergedcomputing.org.grpc.v1.EnsembleOperator/RequestStatus",
            ensemble__service__pb2.StatusRequest.SerializeToString,
            ensemble__service__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RequestAction(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/convergedcomputing.org.grpc.v1.EnsembleOperator/RequestAction",
            ensemble__service__pb2.ActionRequest.SerializeToString,
            ensemble__service__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
